# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: /prod

jobs:
# Please do not rename this job
  build-project:
    name: build Infinity-Jewels
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: mkdir stripe-backend

      - name: Run script
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: cd stripe-backend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: vv22.5.1

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: npm init -y

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: vv22.5.1

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          STRIPE_SECRET_KEY: your_secret_key_here
          STRIPE_WEBHOOK_SECRET: your_webhook_secret_here
        run: npm install express stripe body-parser dotenv

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 5a97d971-08dc-4818-b832-37f1261e1356
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Infinity-Jewels/config.yaml
          action: upload
